name: test-workflow

on: push

defaults:
  run:
    shell: bash -l {0}
jobs:
  test-gha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: api/allen.yaml
          cache-downloads: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('hello_cargo/Cargo.lock') }}

      - name: Ensure env is activated
        run: |
          micromamba activate allen
          rustup default nightly
          cargo build --manifest-path hello_cargo/Cargo.toml
          maturin build --manifest-path hello_cargo/Cargo.toml
      # - uses: messense/maturin-action@v1
      #   with:
      #     maturin-version: latest
      #     command: build
      #     args: --release --manifest-path hello_cargo/Cargo.toml

      - name: python verison
        run: python -V

      - name: find cargo
        run: ls ~/.cargo
        
