name: test-workflow

on: push

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_RELEASE_OPT_LEVEL: 1
  CARGO_PROFILE_RELEASE_DEBUG: 0

defaults:
  run:
    shell: bash -l {0}
jobs:
  test-gha:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - uses: docker://redis
        with:
          entrypoint: /usr/local/bin/redis-server
          args: --appendonly yes --save 60 1 

      - name: ps
        run: docker ps
      # - name: run redis
      #   run: | 
      #     docker run -p 6379:6379 redis redis-server --appendonly yes --save 60 1 &
      
      # - uses: shogo82148/actions-setup-redis@v1
      #   with:
      #     redis-conf: |
      #       appendonly yes 
      #       save 60 1
        
      # - name: config
      #   run: |
      #     redis-cli
      #     config get appendonly
      #     config get save


      # - name: Install Conda environment with Micromamba
      #   uses: mamba-org/provision-with-micromamba@main
      #   with:
      #     environment-file: api/allen.yaml
      #     cache-downloads: true
      #     cache-env: true
 
      # - name: Activate env
      #   run: micromamba activate allen

      # - name: Select nightly
      #   run: rustup default nightly
        
      # - uses: Swatinem/rust-cache@v1.4.0 
      #   with:
      #     working-directory: 
      #     cache-on-failure: true

      # - name: just cargo build
      #   run: cargo build --manifest-path Cargo.toml

      # - name: Maturin build
      #   run: maturin build --manifest-path Cargo.toml
      # - uses: messense/maturin-action@v1
      #   with:
      #     maturin-version: latest
      #     command: build
      #     args: --release --manifest-path hello_cargo/Cargo.toml

