name: test-workflow

on: push

defaults:
  run:
    shell: bash -l {0}
jobs:
  test-gha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: api/allen.yaml
          cache-downloads: true

      - name: env
        run: micromamba env list
        
      - uses: messense/maturin-action@v1
        with:
          working-directory: api
          maturin-version: latest
          command: build
          args: --release