name: test-workflow1

on:
  push:
  pull_request: 

jobs:
  sample-job:
    runs-on: ubuntu-latest
  
    steps:
      - name: fail
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 91.6-eser
      - run: firefox --version
