name: test-workflow1

on:
  push:
  pull_request: 

jobs:
  sample-job:  
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    services:
      redis:
        image: redis
    container:
      image: cypress/browsers:node16.14.2-slim-chrome103-ff102 
    steps:
      # - uses: actions/setup-python@v4
      - name: Checkout 
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - run: python location.py
      # - name: Install Micromamba env
      #   uses: mamba-org/provision-with-micromamba@main
      #   with:
      #     environment-file: api/allen.yml
      #     cache-env: true
      #     cache-env-key: ${{ runner.os }}-${{ hashFiles('api/allen.yml') }}

      # - name: Activate env
      #   run: |
      #     micromamba activate allen

      # - run: uvicorn api.test-api:app &

      # - run: "curl localhost:8000"

      # #   with:
      #     python-version: '3.10'
      # - run: python --version
      # - name: Checkout
      #   uses: actions/checkout@v3
        
      # - uses: actions/cache@v3
      #   id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # - name: Cache Cypress binary
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/Cypress
      #     key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
