name: "Cypress Testing"
on:
  push:
  pull_request:
jobs:
  pre: 
    name: Init
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.url.outputs.url }}
    steps:
    - id: url
      name: Set URL
      run: |
        echo here on test-branch 