name: "GHA Test"
on: 
  push: 
jobs: 
  info: 
    runs-on: ubuntu-latest
    if: > 
      contains(fromJSON('["main", "testing"]'), github.ref_name) ||
      contains(github.ref_type, 'tag') ||
      contains(github.event.head_commit.message, ':build')
    steps:
    - name: Ref
      run: echo ${{ github.ref_name }}
    - name: Type
      run: echo ${{  github.ref_type }}
  job1:
    runs-on: ubuntu-latest
    if: > 
      contains(fromJSON('["main", "testing"]'), github.ref_name) ||
      contains(github.ref_type, 'tag') ||
      contains(github.event.head_commit.message, ':build')
    steps:
    - name: step 1
      run: echo test step 1 
    - name: step 2
      run: echo test step 2 
  job2:
    runs-on: ubuntu-latest
    if: > 
      contains(fromJSON('["main", "testing"]'), github.ref_name) ||
      contains(github.ref_type, 'tag') ||
      contains(github.event.head_commit.message, ':build')
    steps:
    - name: step 1
      run: echo test step 1 
    - name: step 2
      run: echo test step 2 