name: "GHA Test"
on:
  push: 
jobs: 
  info: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - id: test
        name: docker build
        # run: $(exit 2); if echo "exit_code=$?"  >> $GITHUB_OUTPUT
        run: docker build -t test-app .
      - id: exit
        name: docker run 
        run: $(docker run test-app) echo "exit_code=1" >> $GITHUB_OUTPUT
      - if: ${{ steps.exit.outputs.exit_code == 2 }}
        name: echo res
        run: echo ${{ steps.exit.outputs.exit_code }} 