name: test-workflow1

on:
  push:

jobs:
  # j1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Detect file changes  
  #       run: sleep 5m
  j2: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo ${secrets.GITHUB_TOKEN}

