name: "GHA Test"
on:
  push: 
jobs: 
  info: 
    runs-on: ubuntu-latest
    steps:
      - name: ls
        run: ls

      - id: test
        name: docker build
        # run: $(exit 2); if echo "exit_code=$?"  >> $GITHUB_OUTPUT
        run: docker build -t test-app ${{ github.workspace }}
      - id: exit
        name: docker run 
        run: docker run test-app; echo "exit_code=$?" >> $GITHUB_OUTPUT 
      - if: ${{ steps.exit.outputs.exit_code == 2 }}
        name: echo res
        run: echo ${{ steps.test.outputs.exit_code }} 