name: test-workflow1

on:
  push:

jobs:
  j2: 
    runs-on: ubuntu-latest
    steps:
      - uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: "GHA Notifcaiton"
          status: STARTED
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK_URL }}
  