name: "GHA Test"
on:
  push: 
jobs: 
  info: 
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: pwd
        run: exit 1
        continue-on-error: true
      - name: ls
        run: echo ${{ steps.test.outcome }}