name: test-workflow1

on:
  push:
  pull_request: 

jobs:
  sample-job:  
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install env 
        run:  |
          $CONDA/bin/conda env update -f test-app/api/env.yml --name base
      - run: $CONDA/bin/uvicorn --version
      
      # - name: Run GUI
      #   run: |
      #     cd test-app/gui
      #     npm install
      #     npm start &
      
      # - name: Run API
      #   run: |
      #     cd test-app/api
      #     uvicorn api:app &
      
      # - name: Cypress
      #   run: |
      #     cd test-app/gui
      #     npx cypress run
  
    # services:
    #   redis:
    #     image: redis
    # container:
    #   image: cypress/browsers:node16.14.2-slim-chrome103-ff102 
    #   env:
    #     INSIDEDOCKER: 1

    #   # - uses: actions/setup-python@v4
    #   #   with:
    #   #     python-version: '3.10' 

    #   - name: Install Micromamba env
    #     uses: mamba-org/provision-with-micromamba@main
    #     with:
    #       environment-file: api/allen.yml
    #       cache-env: true
    #       cache-env-key: ${{ runner.os }}-${{ hashFiles('api/allen.yml') }}

    #   - run: python location.py
    #   # - name: Activate env
    #   #   run: |
    #   #     micromamba activate allen

    #   - run: uvicorn api.test-api:app &

    #   - run: "curl localhost:8000"

      # - uses: actions/cache@v3
      #   id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # - name: Cache Cypress binary
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/Cypress
      #     key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
