name: test-workflow1

on:
  push:

jobs:
  j1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo j1

      - name: Detect file changes  
        run: echo ${GITHUB_RUN_ID}