name: test-workflow1

on:
  push:
  pull_request: 

jobs:
  sample-job:
    strategy:
      matrix:
        browser: ["chrome", "firefox"]

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install env 
        run:  |
          $CONDA/bin/conda env update -f test-app/api/env.yml --name base
      
      - name: Run API
        run: |
          cd test-app/api
          $CONDA/bin/uvicorn api:app &
      
      - name: Run Cypress  
        uses: cypress-io/github-action@v2
        with:
          working-directory: test-app/gui
          start: npm start
          runTests: false
          # wait-on: "http://localhost:3000"
          # wait-on-timeout: 90
          # browser: ${{matrix.browser}}
          # spec: "cypress/integration/*"
      - run: | 
          test-app/gui
          npx cypress run --browser ${{matrix.browser}}
    # services:
    #   redis:
    #     image: redis
    # container:
    #   image: cypress/browsers:node16.14.2-slim-chrome103-ff102 
    #   env:
    #     INSIDEDOCKER: 1

    #   # - uses: actions/setup-python@v4
    #   #   with:
    #   #     python-version: '3.10' 

    #   - name: Install Micromamba env
    #     uses: mamba-org/provision-with-micromamba@main
    #     with:
    #       environment-file: api/allen.yml
    #       cache-env: true
    #       cache-env-key: ${{ runner.os }}-${{ hashFiles('api/allen.yml') }}

    #   - run: python location.py
    #   # - name: Activate env
    #   #   run: |
    #   #     micromamba activate allen

    #   - run: uvicorn api.test-api:app &

    #   - run: "curl localhost:8000"

      # - uses: actions/cache@v3
      #   id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # - name: Cache Cypress binary
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/Cypress
      #     key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
