name: "GHA Test"
on:
  push: 
jobs:
  basic:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["push", "pull_request"]'), github.ref_name)
    steps:
    - name: echo branch
      run: echo ${{ github.ref_name }}
  job1:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, ':build')
    steps:
    - name: step 1
      run: echo test step 1 
    - name: step 2
      run: echo test step 2 
  job2:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, ':build')
    steps:
    - name: step 1
      run: echo test step 1 
    - name: step 2
      run: echo test step 2 