name: test-workflow1

on:
  push:
  pull_request: 

jobs:
  sample-job:  
    runs-on: ubuntu-22.04
    steps:
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      # - run: python --version
      - run: firefox -v
      - run: sudo apt install firefox; firefox -v
      # - name: Checkout
      #   uses: actions/checkout@v3
        
      # - uses: actions/cache@v3
      #   id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # - name: Cache Cypress binary
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/Cypress
      #     key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
