name: test-workflow1

on:
  push:
  pull_request: 

jobs:
  get-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: |
             const result = await github.request.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.run_id
              });
              console.log(result)
          
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
  # test-api: 
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: exit 1

  # slack-notify:
  #   if: failure() && (github.ref_name == 'main' || github.base_ref == 'main')
  #   runs-on: ubuntu-latest
  #   needs: [test-api]
  #   steps:
  #     - run: echo AS_JOB=SUDALEY >> $GITHUB_ENV
  #     - name: action-slack
  #       uses: 8398a7/action-slack@v3.12.0
  #       with:
  #         mention: ${{fromJSON(secrets.users)[github.actor]}} 
  #         if_mention: always
  #         text: "Check Github Actions"
  #         author_name: ${{github.job}}
  #         status: failure
  #         job_name:
  #         fields: commit, message, job, ref
          
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}