name: test-workflow1

on:
  push:

jobs:
  j2: 
    runs-on: ubuntu-latest
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo 'user={"esudaley":"E S"}' >> $GITHUB_ENV

    - name: Use the value
      id: step_two
      run: |
        echo "${{ fromJSON(env.user).esudaley}}"

    - name: Slack Notification
      uses: lazy-actions/slatify@master
      if: always()
      with:
        type: ${{ job.status}}
        mention: "@E S"
        mention_if: 'success'
        channel: '#gha'
        commit: true
        username: esudaley
        job_name: ${{github.job}}
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
        token: ${{ secrets.GITHUB_TOKEN }}
  