name: test-workflow1

on:
  push:

jobs:
  j2: 
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      # - name: Slack Notification
      #   uses: lazy-actions/slatify@master
      #   if: always()
      #   with:
      #     type: ${{ job.status }}
      #     mention: 'here'
      #     mention_if: 'failure'
      #     channel: '#gha'
      #     commit: true
      #     job_name: ${{github.job}}
      #     url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
        