name: test-workflow1

on:
  push:
  pull_request: 

jobs:

  sample-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install time
        run: npm install