name: test-workflow1

on:
  push:

jobs:
  # j1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Detect file changes  
  #       run: sleep 5m
  j2: 
    runs-on: ubuntu-latest
    steps:
      - run: >-
          curl 
          -X POST 
          -H "Accept: application/vnd.github+json"  
          -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" 
          https://api.github.com/repos/esudaley/gha-test/actions/runs/${GITHUB_RUN_ID}/cancel