name: test-workflow1

on:
  push:
  pull_request: 

jobs:
  sample-job:
    runs-on: ubuntu-latest
  
    steps:
      - name: fail
        run: |
          exit 1
          echo "::set-output name=TEST::strawberry"
        continue-on-error: true
      - run: echo here is ${{toJSON(github.event)}}
