name: test-workflow1

on:
  push:

jobs:
  j2: 
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        
        uses: eugene-babichenko/slack-notifier@v1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL}}
        
  