name: test-workflow1

on:
  push:

jobs:
  j2:
    runs-on: ubuntu-latest
    steps:
      - uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: app-alerts
          status: STARTED
          color: good
        env:  
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK_URL}}
    # - uses: actions/checkout@v2
    # - name: Slack Notification
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
