name: test-workflow1

on:
  push:

jobs:
  test-api: 
    runs-on: ubuntu-latest
    # env: 
    #   users: >-
    #     {
    #     a:1, 
    #     b:2, 
    #     c:3}
    steps:
    # - name: Set the value
    #   id: step_one
    #   run: >-
    #     echo 'user={
    #       "esudaley":"U03SG9FGYHK",
    #       "buddy": "guy"
    #       }' >> $GITHUB_ENV

    # - run: exit 1
      
    - name: action-slack
      if: always()
      uses: 8398a7/action-slack@v3.12.0
      with:
        mention: U03SG9FGYHK
        # mention: ${{fromJSON(env.users)['b']}} 
        if_mention: always
        text: "Check Github Actions"
        author_name: ${{github.job}}
        status: ${{ job.status }}
        fields: job, commit, message, ref
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        user: " ${{fromJSON(secrets.users)['esudaley']}} " 
