name: test-workflow1

on:
  push:

jobs:
  sample-job:
    runs-on: ubuntu-latest
  
    steps:
      - name: Download Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 91.6.0esr