name: test-workflow1

on:
  push:

jobs:
  j2: 
    runs-on: ubuntu-latest
    steps:

      - run: echo ${{job}}
      - run: echo ${{job.container.id}}

      # - name: Slack Notification
      #   uses: lazy-actions/slatify@master
      #   if: always()
      #   with:
      #     type: ${{ job.status }}
      #     mention: 'here'
      #     mention_if: 'failure'
      #     channel: '#gha'
      #     commit: true
      #     job_name: ${{env.GITHUB_JOB}}
      #     url: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
        