name: "GHA Test"
on:
  push: 
jobs: 
  info: 
    runs-on: ubuntu-latest
    steps:
      - name: pwd
        run: exit 1
        continue-on-error: true
      - if: failure()
        name: ls
        run: ls -R