name: "GHA Test"
on:
  push: 
jobs: 
  info: 
    runs-on: ubuntu-latest
    steps:
      - id: test
        name: pwd
        run: $(exit 2) echo 'exit_code=$?'  >>$GITHUB_OUTPUT
        continue-on-error: true
      - name: echo env
        run: echo ${{ needs.test.outputs.exit_code }}