name: test-workflow1

on:
  push:

jobs:
  test-api: 
    runs-on: ubuntu-latest
    env: 
      users: >-
        {
        esudaley:U03SG9FGYHK, 
        b:2, 
        c:3}
    steps:

    # - run: exit 1
      
    - name: action-slack
      if: always()
      uses: 8398a7/action-slack@v3.12.0
      with:
        # mention: U03SG9FGYHK
        # mention: ${{fromJSON(env.users)['b']}} 
        mention: ${{fromJSON(env.users.github.actor)}} 
        if_mention: always
        text: "Check Github Actions"
        author_name: ${{github.job}}
        status: ${{ job.status }}
        fields: job, commit, message, ref
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # user: ${{fromJSON(secrets.users)['esudaley']}} 
